services:
  app:
    build: .
    ports:
      - "8000:8000"
    links:
      - "db:database"
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/storage
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
    ports:
      - "5432:5432"
